"""Domain entities, value objects, and schemas."""

import uuid
from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class TaskStatus(str, Enum):
    """Execution status of an agent task."""

    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"


class CityWeather(BaseModel):
    """Value object representing the weather condition of a city."""

    model_config = ConfigDict(frozen=True)

    city: str
    temperature_celsius: float
    condition: str
    humidity_percent: int


class CalculationResult(BaseModel):
    """Value object representing an arithmetic computation result."""

    model_config = ConfigDict(frozen=True)

    expression: str
    result: float


class AgentTask(BaseModel):
    """Domain entity representing a task submitted to an agent."""

    task_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    goal: str
    context: dict[str, Any] = Field(default_factory=dict)
    correlation_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    status: TaskStatus = Field(default=TaskStatus.PENDING)


class AgentResponse(BaseModel):
    """Value object representing the output generated by an agent."""

    model_config = ConfigDict(frozen=True)

    task_id: str
    output: str
    success: bool = True
    sub_agent_name: str | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)


class AgentCard(BaseModel):
    """A2A protocol agent discovery metadata card."""

    name: str
    description: str
    version: str = "1.0.0"
    capabilities: list[str] = Field(default_factory=list)
    endpoints: dict[str, str] = Field(default_factory=dict)
